//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Alumno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Alumno()
        {
            this.TB_Matricula = new HashSet<TB_Matricula>();
        }
    
        public string IdAlum { get; set; }
        public string Ndocum { get; set; }
        public string NomAlu { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public string TelAlu { get; set; }
        public string CorAlu { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string Sexoal { get; set; }
        public Nullable<System.DateTime> FecNac { get; set; }
        public string CodCar { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string direccion { get; set; }
        public string Id_Ubi { get; set; }
        public byte[] foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Matricula> TB_Matricula { get; set; }
        public virtual Tb_Carrera Tb_Carrera { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
    }
}
