//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Matricula
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Matricula()
        {
            this.Tb_Seccion = new HashSet<Tb_Seccion>();
        }
    
        public string NroMat { get; set; }
        public string IdSeme { get; set; }
        public byte EstMat { get; set; }
        public string IdAlum { get; set; }
        public Nullable<System.DateTime> FecMat { get; set; }
        public string CodCar { get; set; }
    
        public virtual TB_Alumno TB_Alumno { get; set; }
        public virtual TB_Semestre TB_Semestre { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Seccion> Tb_Seccion { get; set; }
    }
}
