//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_Profesor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_Profesor()
        {
            this.Tb_Seccion = new HashSet<Tb_Seccion>();
            this.TB_Espc_Prof = new HashSet<TB_Espc_Prof>();
        }
    
        public string IdProf { get; set; }
        public string Ndocum { get; set; }
        public string NomPro { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public string CorIns { get; set; }
        public string TelPro { get; set; }
        public Nullable<System.DateTime> FecNac { get; set; }
        public string Sexopr { get; set; }
        public Nullable<System.DateTime> FecIng { get; set; }
        public Nullable<bool> Estado { get; set; }
        public Nullable<System.DateTime> Fec_Registro { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public string direccion { get; set; }
        public string Id_Ubi { get; set; }
        public byte[] Foto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Seccion> Tb_Seccion { get; set; }
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_Espc_Prof> TB_Espc_Prof { get; set; }
    }
}
