//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class VerDetAlum
    {
        public string Id { get; set; }
        public string Alumno { get; set; }
        public string Genero { get; set; }
        public string DNI { get; set; }
        public string Correo { get; set; }
        public string Carrera { get; set; }
        public string Facultad { get; set; }
        public string Estado { get; set; }
        public string Distrito { get; set; }
    }
}
