//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_alumno
    {
        public string ID { get; set; }
        public string DNI { get; set; }
        public string Alumno { get; set; }
        public string Direccion { get; set; }
        public byte[] Foto { get; set; }
        public string Telefono { get; set; }
        public string Correo { get; set; }
        public string Estado { get; set; }
        public string Genero { get; set; }
        public Nullable<System.DateTime> Fecha_nacimiento { get; set; }
        public string Departamento { get; set; }
        public string Carrera { get; set; }
        public string Facultad { get; set; }
        public Nullable<System.DateTime> Fecha_Registro { get; set; }
        public string Registro { get; set; }
        public Nullable<System.DateTime> Ultima_modificacion { get; set; }
        public string Usuario_ultima_modificacion { get; set; }
    }
}
