//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_AlumnoCursos
    {
        public string IdAlum { get; set; }
        public Nullable<System.DateTime> FecMat { get; set; }
        public string Descrp { get; set; }
        public Nullable<System.DateTime> FecIni { get; set; }
        public Nullable<System.DateTime> FecFin { get; set; }
        public string CodCar { get; set; }
        public string NomCur { get; set; }
        public string Activo { get; set; }
        public string DIA { get; set; }
        public Nullable<System.TimeSpan> HorIni { get; set; }
        public Nullable<System.TimeSpan> HorFin { get; set; }
        public string Desloc { get; set; }
        public string IdAula { get; set; }
    }
}
