//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConsultaListaAlumnoCurso
    {
        public string IdAlum { get; set; }
        public string Ndocum { get; set; }
        public string NomAlu { get; set; }
        public string ApePat { get; set; }
        public string ApeMat { get; set; }
        public string TelAlu { get; set; }
        public string CorAlu { get; set; }
        public Nullable<bool> Estado { get; set; }
        public string DesFac { get; set; }
        public string DesCar { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
    }
}
