//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_CarreraXGenero
    {
        public Nullable<int> Mujeres { get; set; }
        public Nullable<int> Hombres { get; set; }
        public string DesCar { get; set; }
        public Nullable<int> Total { get; set; }
    }
}
