//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_ConsultaProfesorCurso
    {
        public string Cod { get; set; }
        public string DNI { get; set; }
        public string Nombre_y_Apellido { get; set; }
        public string Día { get; set; }
        public Nullable<System.TimeSpan> Hora_Inicio { get; set; }
        public Nullable<System.TimeSpan> Hora_Fin { get; set; }
        public string Nombre_Curso { get; set; }
        public string Estado { get; set; }
        public string Centro { get; set; }
        public string Aula { get; set; }
    }
}
