//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Matricula
    {
        public string Ciclo { get; set; }
        public string Matricula { get; set; }
        public string Estado { get; set; }
        public string Alumno { get; set; }
        public string Carrera { get; set; }
        public Nullable<System.DateTime> Inscrito { get; set; }
    }
}
