//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Profesor
    {
        public string Id { get; set; }
        public string Profesor { get; set; }
        public string Correo { get; set; }
        public byte[] Foto { get; set; }
        public string Genero { get; set; }
        public string Telefono { get; set; }
        public string DNI { get; set; }
        public Nullable<System.DateTime> Fecha_Ingreso { get; set; }
        public string Estado { get; set; }
        public string Departamento { get; set; }
    }
}
