//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCG_Institutec
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_preMatricula
    {
        public string NRC { get; set; }
        public string Curso { get; set; }
        public string Profesor { get; set; }
        public string Estado { get; set; }
        public string Local { get; set; }
        public string DIA { get; set; }
        public Nullable<System.TimeSpan> Inicio { get; set; }
        public Nullable<System.TimeSpan> Fin { get; set; }
        public string Carrera { get; set; }
        public Nullable<byte> Vacant { get; set; }
    }
}
