//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyCarrera
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarreraDC", Namespace="http://schemas.datacontract.org/2004/07/WCG_Institutec")]
    public partial class CarreraDC : object
    {
        
        private string CodCarField;
        
        private string DesCarField;
        
        private string DesFacField;
        
        private short Est_carrField;
        
        private string Est_carr_StringField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private string IdFacuField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCar
        {
            get
            {
                return this.CodCarField;
            }
            set
            {
                this.CodCarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesCar
        {
            get
            {
                return this.DesCarField;
            }
            set
            {
                this.DesCarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesFac
        {
            get
            {
                return this.DesFacField;
            }
            set
            {
                this.DesFacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Est_carr
        {
            get
            {
                return this.Est_carrField;
            }
            set
            {
                this.Est_carrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Est_carr_String
        {
            get
            {
                return this.Est_carr_StringField;
            }
            set
            {
                this.Est_carr_StringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFacu
        {
            get
            {
                return this.IdFacuField;
            }
            set
            {
                this.IdFacuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCarrera.IServicioCarrera")]
    public interface IServicioCarrera
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCarrera/ListarCarrera", ReplyAction="http://tempuri.org/IServicioCarrera/ListarCarreraResponse")]
        System.Collections.Generic.List<ProxyCarrera.CarreraDC> ListarCarrera();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCarrera/ListarCarrera", ReplyAction="http://tempuri.org/IServicioCarrera/ListarCarreraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCarrera.CarreraDC>> ListarCarreraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCarrera/ObtenerCarreraAlumno", ReplyAction="http://tempuri.org/IServicioCarrera/ObtenerCarreraAlumnoResponse")]
        string ObtenerCarreraAlumno(string IdAlum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCarrera/ObtenerCarreraAlumno", ReplyAction="http://tempuri.org/IServicioCarrera/ObtenerCarreraAlumnoResponse")]
        System.Threading.Tasks.Task<string> ObtenerCarreraAlumnoAsync(string IdAlum);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioCarreraChannel : ProxyCarrera.IServicioCarrera, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioCarreraClient : System.ServiceModel.ClientBase<ProxyCarrera.IServicioCarrera>, ProxyCarrera.IServicioCarrera
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioCarreraClient() : 
                base(ServicioCarreraClient.GetDefaultBinding(), ServicioCarreraClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioCarrera.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCarreraClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioCarreraClient.GetBindingForEndpoint(endpointConfiguration), ServicioCarreraClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCarreraClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioCarreraClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCarreraClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioCarreraClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioCarreraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyCarrera.CarreraDC> ListarCarrera()
        {
            return base.Channel.ListarCarrera();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyCarrera.CarreraDC>> ListarCarreraAsync()
        {
            return base.Channel.ListarCarreraAsync();
        }
        
        public string ObtenerCarreraAlumno(string IdAlum)
        {
            return base.Channel.ObtenerCarreraAlumno(IdAlum);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerCarreraAlumnoAsync(string IdAlum)
        {
            return base.Channel.ObtenerCarreraAlumnoAsync(IdAlum);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCarrera))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioCarrera))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCG_Institutec/ServicioCarrera/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioCarreraClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioCarrera);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioCarreraClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioCarrera);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioCarrera,
        }
    }
}
