//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyFacultad
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacultadDC", Namespace="http://schemas.datacontract.org/2004/07/WCG_Institutec")]
    public partial class FacultadDC : object
    {
        
        private string DesFacField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private string IdFacuField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesFac
        {
            get
            {
                return this.DesFacField;
            }
            set
            {
                this.DesFacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFacu
        {
            get
            {
                return this.IdFacuField;
            }
            set
            {
                this.IdFacuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyFacultad.IServicioFacultad")]
    public interface IServicioFacultad
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/ListarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/ListarFacultadResponse")]
        System.Collections.Generic.List<ProxyFacultad.FacultadDC> ListarFacultad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/ListarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/ListarFacultadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFacultad.FacultadDC>> ListarFacultadAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/ConsultarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/ConsultarFacultadResponse")]
        ProxyFacultad.FacultadDC ConsultarFacultad(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/ConsultarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/ConsultarFacultadResponse")]
        System.Threading.Tasks.Task<ProxyFacultad.FacultadDC> ConsultarFacultadAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/ActualizarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/ActualizarFacultadResponse")]
        bool ActualizarFacultad(ProxyFacultad.FacultadDC objFacultadDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/ActualizarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/ActualizarFacultadResponse")]
        System.Threading.Tasks.Task<bool> ActualizarFacultadAsync(ProxyFacultad.FacultadDC objFacultadDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/EliminarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/EliminarFacultadResponse")]
        bool EliminarFacultad(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioFacultad/EliminarFacultad", ReplyAction="http://tempuri.org/IServicioFacultad/EliminarFacultadResponse")]
        System.Threading.Tasks.Task<bool> EliminarFacultadAsync(string strCodigo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioFacultadChannel : ProxyFacultad.IServicioFacultad, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioFacultadClient : System.ServiceModel.ClientBase<ProxyFacultad.IServicioFacultad>, ProxyFacultad.IServicioFacultad
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioFacultadClient() : 
                base(ServicioFacultadClient.GetDefaultBinding(), ServicioFacultadClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioFacultad.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacultadClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioFacultadClient.GetBindingForEndpoint(endpointConfiguration), ServicioFacultadClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacultadClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioFacultadClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacultadClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioFacultadClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioFacultadClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyFacultad.FacultadDC> ListarFacultad()
        {
            return base.Channel.ListarFacultad();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyFacultad.FacultadDC>> ListarFacultadAsync()
        {
            return base.Channel.ListarFacultadAsync();
        }
        
        public ProxyFacultad.FacultadDC ConsultarFacultad(string strCodigo)
        {
            return base.Channel.ConsultarFacultad(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyFacultad.FacultadDC> ConsultarFacultadAsync(string strCodigo)
        {
            return base.Channel.ConsultarFacultadAsync(strCodigo);
        }
        
        public bool ActualizarFacultad(ProxyFacultad.FacultadDC objFacultadDC)
        {
            return base.Channel.ActualizarFacultad(objFacultadDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarFacultadAsync(ProxyFacultad.FacultadDC objFacultadDC)
        {
            return base.Channel.ActualizarFacultadAsync(objFacultadDC);
        }
        
        public bool EliminarFacultad(string strCodigo)
        {
            return base.Channel.EliminarFacultad(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarFacultadAsync(string strCodigo)
        {
            return base.Channel.EliminarFacultadAsync(strCodigo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioFacultad))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioFacultad))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCG_Institutec/ServicioFacultad/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioFacultadClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioFacultad);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioFacultadClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioFacultad);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioFacultad,
        }
    }
}
