//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_Institutec.ProxySeccion {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxySeccion.IServicioSeccion")]
    public interface IServicioSeccion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/EliminarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/EliminarSeccionResponse")]
        bool EliminarSeccion(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/EliminarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/EliminarSeccionResponse")]
        System.Threading.Tasks.Task<bool> EliminarSeccionAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ConsultarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ConsultarSeccionResponse")]
        WCG_Institutec.SeccionDC ConsultarSeccion(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ConsultarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ConsultarSeccionResponse")]
        System.Threading.Tasks.Task<WCG_Institutec.SeccionDC> ConsultarSeccionAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ListarSeccionResponse")]
        WCG_Institutec.SeccionDC[] ListarSeccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ListarSeccionResponse")]
        System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarSeccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ActualizarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ActualizarSeccionResponse")]
        bool ActualizarSeccion(WCG_Institutec.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ActualizarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/ActualizarSeccionResponse")]
        System.Threading.Tasks.Task<bool> ActualizarSeccionAsync(WCG_Institutec.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/InsertarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/InsertarSeccionResponse")]
        bool InsertarSeccion(WCG_Institutec.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/InsertarSeccion", ReplyAction="http://tempuri.org/IServicioSeccion/InsertarSeccionResponse")]
        System.Threading.Tasks.Task<bool> InsertarSeccionAsync(WCG_Institutec.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarCursos", ReplyAction="http://tempuri.org/IServicioSeccion/ListarCursosResponse")]
        WCG_Institutec.SeccionDC[] ListarCursos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarCursos", ReplyAction="http://tempuri.org/IServicioSeccion/ListarCursosResponse")]
        System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarCursosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarProfesores", ReplyAction="http://tempuri.org/IServicioSeccion/ListarProfesoresResponse")]
        WCG_Institutec.SeccionDC[] ListarProfesores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarProfesores", ReplyAction="http://tempuri.org/IServicioSeccion/ListarProfesoresResponse")]
        System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarProfesoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarLocales", ReplyAction="http://tempuri.org/IServicioSeccion/ListarLocalesResponse")]
        WCG_Institutec.SeccionDC[] ListarLocales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSeccion/ListarLocales", ReplyAction="http://tempuri.org/IServicioSeccion/ListarLocalesResponse")]
        System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarLocalesAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSeccionChannel : Test_Institutec.ProxySeccion.IServicioSeccion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSeccionClient : System.ServiceModel.ClientBase<Test_Institutec.ProxySeccion.IServicioSeccion>, Test_Institutec.ProxySeccion.IServicioSeccion {
        
        public ServicioSeccionClient() {
        }
        
        public ServicioSeccionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSeccionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSeccionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSeccionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EliminarSeccion(string strCodigo) {
            return base.Channel.EliminarSeccion(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarSeccionAsync(string strCodigo) {
            return base.Channel.EliminarSeccionAsync(strCodigo);
        }
        
        public WCG_Institutec.SeccionDC ConsultarSeccion(string strCodigo) {
            return base.Channel.ConsultarSeccion(strCodigo);
        }
        
        public System.Threading.Tasks.Task<WCG_Institutec.SeccionDC> ConsultarSeccionAsync(string strCodigo) {
            return base.Channel.ConsultarSeccionAsync(strCodigo);
        }
        
        public WCG_Institutec.SeccionDC[] ListarSeccion() {
            return base.Channel.ListarSeccion();
        }
        
        public System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarSeccionAsync() {
            return base.Channel.ListarSeccionAsync();
        }
        
        public bool ActualizarSeccion(WCG_Institutec.SeccionDC objSeccionDC) {
            return base.Channel.ActualizarSeccion(objSeccionDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarSeccionAsync(WCG_Institutec.SeccionDC objSeccionDC) {
            return base.Channel.ActualizarSeccionAsync(objSeccionDC);
        }
        
        public bool InsertarSeccion(WCG_Institutec.SeccionDC objSeccionDC) {
            return base.Channel.InsertarSeccion(objSeccionDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarSeccionAsync(WCG_Institutec.SeccionDC objSeccionDC) {
            return base.Channel.InsertarSeccionAsync(objSeccionDC);
        }
        
        public WCG_Institutec.SeccionDC[] ListarCursos() {
            return base.Channel.ListarCursos();
        }
        
        public System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarCursosAsync() {
            return base.Channel.ListarCursosAsync();
        }
        
        public WCG_Institutec.SeccionDC[] ListarProfesores() {
            return base.Channel.ListarProfesores();
        }
        
        public System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarProfesoresAsync() {
            return base.Channel.ListarProfesoresAsync();
        }
        
        public WCG_Institutec.SeccionDC[] ListarLocales() {
            return base.Channel.ListarLocales();
        }
        
        public System.Threading.Tasks.Task<WCG_Institutec.SeccionDC[]> ListarLocalesAsync() {
            return base.Channel.ListarLocalesAsync();
        }
    }
}
