//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyProfesor
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDC", Namespace="http://schemas.datacontract.org/2004/07/WCG_Institutec")]
    public partial class ProfesorDC : object
    {
        
        private string ApeMatField;
        
        private string ApePatField;
        
        private string ApellPat_MatField;
        
        private string CorInsField;
        
        private string DireccionField;
        
        private bool EstadoField;
        
        private string EstadoTextoField;
        
        private System.DateTime FecIngField;
        
        private System.DateTime FecNacField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private byte[] FotoField;
        
        private string FullnameField;
        
        private string IdProfField;
        
        private string Id_UbiField;
        
        private string NdocumField;
        
        private string NomProField;
        
        private string SexoprField;
        
        private string TelProField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMat
        {
            get
            {
                return this.ApeMatField;
            }
            set
            {
                this.ApeMatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePat
        {
            get
            {
                return this.ApePatField;
            }
            set
            {
                this.ApePatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellPat_Mat
        {
            get
            {
                return this.ApellPat_MatField;
            }
            set
            {
                this.ApellPat_MatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorIns
        {
            get
            {
                return this.CorInsField;
            }
            set
            {
                this.CorInsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoTexto
        {
            get
            {
                return this.EstadoTextoField;
            }
            set
            {
                this.EstadoTextoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecIng
        {
            get
            {
                return this.FecIngField;
            }
            set
            {
                this.FecIngField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNac
        {
            get
            {
                return this.FecNacField;
            }
            set
            {
                this.FecNacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Fullname
        {
            get
            {
                return this.FullnameField;
            }
            set
            {
                this.FullnameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProf
        {
            get
            {
                return this.IdProfField;
            }
            set
            {
                this.IdProfField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubi
        {
            get
            {
                return this.Id_UbiField;
            }
            set
            {
                this.Id_UbiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ndocum
        {
            get
            {
                return this.NdocumField;
            }
            set
            {
                this.NdocumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomPro
        {
            get
            {
                return this.NomProField;
            }
            set
            {
                this.NomProField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexopr
        {
            get
            {
                return this.SexoprField;
            }
            set
            {
                this.SexoprField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelPro
        {
            get
            {
                return this.TelProField;
            }
            set
            {
                this.TelProField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyProfesor.IServicioProfesor")]
    public interface IServicioProfesor
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        bool InsertarProfesor(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        System.Threading.Tasks.Task<bool> InsertarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        bool ActualizarProfesor(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        bool EliminarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        ProxyProfesor.ProfesorDC ConsultarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        System.Threading.Tasks.Task<ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorResponse")]
        System.Collections.Generic.List<ProxyProfesor.ProfesorDC> ListarProfesor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyProfesor.ProfesorDC>> ListarProfesorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesorEspecialidad", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorEspecialidadResponse")]
        System.Collections.Generic.List<ProxyProfesor.ProfesorDC> ListarProfesorEspecialidad(int num_esp);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesorEspecialidad", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesorEspecialidadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyProfesor.ProfesorDC>> ListarProfesorEspecialidadAsync(int num_esp);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioProfesorChannel : ProxyProfesor.IServicioProfesor, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioProfesorClient : System.ServiceModel.ClientBase<ProxyProfesor.IServicioProfesor>, ProxyProfesor.IServicioProfesor
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioProfesorClient() : 
                base(ServicioProfesorClient.GetDefaultBinding(), ServicioProfesorClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioProfesor.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioProfesorClient.GetBindingForEndpoint(endpointConfiguration), ServicioProfesorClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioProfesorClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioProfesorClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioProfesorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertarProfesor(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.InsertarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.InsertarProfesorAsync(objProfesorDC);
        }
        
        public bool ActualizarProfesor(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.ActualizarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(ProxyProfesor.ProfesorDC objProfesorDC)
        {
            return base.Channel.ActualizarProfesorAsync(objProfesorDC);
        }
        
        public bool EliminarProfesor(string strCodigo)
        {
            return base.Channel.EliminarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo)
        {
            return base.Channel.EliminarProfesorAsync(strCodigo);
        }
        
        public ProxyProfesor.ProfesorDC ConsultarProfesor(string strCodigo)
        {
            return base.Channel.ConsultarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(string strCodigo)
        {
            return base.Channel.ConsultarProfesorAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyProfesor.ProfesorDC> ListarProfesor()
        {
            return base.Channel.ListarProfesor();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyProfesor.ProfesorDC>> ListarProfesorAsync()
        {
            return base.Channel.ListarProfesorAsync();
        }
        
        public System.Collections.Generic.List<ProxyProfesor.ProfesorDC> ListarProfesorEspecialidad(int num_esp)
        {
            return base.Channel.ListarProfesorEspecialidad(num_esp);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyProfesor.ProfesorDC>> ListarProfesorEspecialidadAsync(int num_esp)
        {
            return base.Channel.ListarProfesorEspecialidadAsync(num_esp);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioProfesor))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioProfesor))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCG_Institutec/ServicioProfesor/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioProfesorClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioProfesor);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioProfesorClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioProfesor);
        }

       

        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioProfesor,
        }
    }
}
