//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyAlumno
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AlumnoDC", Namespace="http://schemas.datacontract.org/2004/07/WCG_Institutec")]
    public partial class AlumnoDC : object
    {
        
        private string ApeMatField;
        
        private string ApePatField;
        
        private string CodCarField;
        
        private string CorAluField;
        
        private string DesCarField;
        
        private string DesFacField;
        
        private bool EstadoField;
        
        private System.DateTime FecNacField;
        
        private System.DateTime Fec_RegistroField;
        
        private System.DateTime Fec_Ult_ModField;
        
        private byte[] FotoField;
        
        private string IdAlumField;
        
        private string IdFacuField;
        
        private string Id_UbiField;
        
        private string NdocumField;
        
        private string NomAluField;
        
        private string NomCurField;
        
        private string NrcField;
        
        private string SexoalField;
        
        private string TelAluField;
        
        private string Usu_RegistroField;
        
        private string Usu_Ult_ModField;
        
        private string departamentoField;
        
        private string direccionField;
        
        private string distritoField;
        
        private string fullNameField;
        
        private string provinciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApeMat
        {
            get
            {
                return this.ApeMatField;
            }
            set
            {
                this.ApeMatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApePat
        {
            get
            {
                return this.ApePatField;
            }
            set
            {
                this.ApePatField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodCar
        {
            get
            {
                return this.CodCarField;
            }
            set
            {
                this.CodCarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CorAlu
        {
            get
            {
                return this.CorAluField;
            }
            set
            {
                this.CorAluField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesCar
        {
            get
            {
                return this.DesCarField;
            }
            set
            {
                this.DesCarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesFac
        {
            get
            {
                return this.DesFacField;
            }
            set
            {
                this.DesFacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FecNac
        {
            get
            {
                return this.FecNacField;
            }
            set
            {
                this.FecNacField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Registro
        {
            get
            {
                return this.Fec_RegistroField;
            }
            set
            {
                this.Fec_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod
        {
            get
            {
                return this.Fec_Ult_ModField;
            }
            set
            {
                this.Fec_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto
        {
            get
            {
                return this.FotoField;
            }
            set
            {
                this.FotoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdAlum
        {
            get
            {
                return this.IdAlumField;
            }
            set
            {
                this.IdAlumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdFacu
        {
            get
            {
                return this.IdFacuField;
            }
            set
            {
                this.IdFacuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubi
        {
            get
            {
                return this.Id_UbiField;
            }
            set
            {
                this.Id_UbiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ndocum
        {
            get
            {
                return this.NdocumField;
            }
            set
            {
                this.NdocumField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomAlu
        {
            get
            {
                return this.NomAluField;
            }
            set
            {
                this.NomAluField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NomCur
        {
            get
            {
                return this.NomCurField;
            }
            set
            {
                this.NomCurField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nrc
        {
            get
            {
                return this.NrcField;
            }
            set
            {
                this.NrcField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexoal
        {
            get
            {
                return this.SexoalField;
            }
            set
            {
                this.SexoalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TelAlu
        {
            get
            {
                return this.TelAluField;
            }
            set
            {
                this.TelAluField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro
        {
            get
            {
                return this.Usu_RegistroField;
            }
            set
            {
                this.Usu_RegistroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod
        {
            get
            {
                return this.Usu_Ult_ModField;
            }
            set
            {
                this.Usu_Ult_ModField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string departamento
        {
            get
            {
                return this.departamentoField;
            }
            set
            {
                this.departamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string direccion
        {
            get
            {
                return this.direccionField;
            }
            set
            {
                this.direccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string distrito
        {
            get
            {
                return this.distritoField;
            }
            set
            {
                this.distritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string fullName
        {
            get
            {
                return this.fullNameField;
            }
            set
            {
                this.fullNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string provincia
        {
            get
            {
                return this.provinciaField;
            }
            set
            {
                this.provinciaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyAlumno.IServicioAlumno")]
    public interface IServicioAlumno
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/InsertarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/InsertarAlumnoResponse")]
        bool InsertarAlumno(ProxyAlumno.AlumnoDC objAlumnoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/InsertarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/InsertarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> InsertarAlumnoAsync(ProxyAlumno.AlumnoDC objAlumnoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ActualizarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ActualizarAlumnoResponse")]
        bool ActualizarAlumno(ProxyAlumno.AlumnoDC objAlumnoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ActualizarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ActualizarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarAlumnoAsync(ProxyAlumno.AlumnoDC objAlumnoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/EliminarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/EliminarAlumnoResponse")]
        bool EliminarAlumno(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/EliminarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/EliminarAlumnoResponse")]
        System.Threading.Tasks.Task<bool> EliminarAlumnoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoResponse")]
        ProxyAlumno.AlumnoDC ConsultarAlumno(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ConsultarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ConsultarAlumnoResponse")]
        System.Threading.Tasks.Task<ProxyAlumno.AlumnoDC> ConsultarAlumnoAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ListarAlumnoResponse")]
        System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarAlumno();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ListarAlumnoResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarAlumnoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarAlumnoNRC", ReplyAction="http://tempuri.org/IServicioAlumno/ListarAlumnoNRCResponse")]
        System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarAlumnoNRC(string Nrc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarAlumnoNRC", ReplyAction="http://tempuri.org/IServicioAlumno/ListarAlumnoNRCResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarAlumnoNRCAsync(string Nrc);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ObtenerFacultadAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ObtenerFacultadAlumnoResponse")]
        string ObtenerFacultadAlumno(string strIdAlum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ObtenerFacultadAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ObtenerFacultadAlumnoResponse")]
        System.Threading.Tasks.Task<string> ObtenerFacultadAlumnoAsync(string strIdAlum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ObtenerCarreraAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ObtenerCarreraAlumnoResponse")]
        string ObtenerCarreraAlumno(string strIdAlum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ObtenerCarreraAlumno", ReplyAction="http://tempuri.org/IServicioAlumno/ObtenerCarreraAlumnoResponse")]
        System.Threading.Tasks.Task<string> ObtenerCarreraAlumnoAsync(string strIdAlum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarCarrera", ReplyAction="http://tempuri.org/IServicioAlumno/ListarCarreraResponse")]
        System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarCarrera();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarCarrera", ReplyAction="http://tempuri.org/IServicioAlumno/ListarCarreraResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarCarreraAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarFacultad", ReplyAction="http://tempuri.org/IServicioAlumno/ListarFacultadResponse")]
        System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarFacultad();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioAlumno/ListarFacultad", ReplyAction="http://tempuri.org/IServicioAlumno/ListarFacultadResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarFacultadAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioAlumnoChannel : ProxyAlumno.IServicioAlumno, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioAlumnoClient : System.ServiceModel.ClientBase<ProxyAlumno.IServicioAlumno>, ProxyAlumno.IServicioAlumno
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioAlumnoClient() : 
                base(ServicioAlumnoClient.GetDefaultBinding(), ServicioAlumnoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioAlumno.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAlumnoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioAlumnoClient.GetBindingForEndpoint(endpointConfiguration), ServicioAlumnoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAlumnoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioAlumnoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAlumnoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioAlumnoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioAlumnoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public bool InsertarAlumno(ProxyAlumno.AlumnoDC objAlumnoDC)
        {
            return base.Channel.InsertarAlumno(objAlumnoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarAlumnoAsync(ProxyAlumno.AlumnoDC objAlumnoDC)
        {
            return base.Channel.InsertarAlumnoAsync(objAlumnoDC);
        }
        
        public bool ActualizarAlumno(ProxyAlumno.AlumnoDC objAlumnoDC)
        {
            return base.Channel.ActualizarAlumno(objAlumnoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarAlumnoAsync(ProxyAlumno.AlumnoDC objAlumnoDC)
        {
            return base.Channel.ActualizarAlumnoAsync(objAlumnoDC);
        }
        
        public bool EliminarAlumno(string strCodigo)
        {
            return base.Channel.EliminarAlumno(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarAlumnoAsync(string strCodigo)
        {
            return base.Channel.EliminarAlumnoAsync(strCodigo);
        }
        
        public ProxyAlumno.AlumnoDC ConsultarAlumno(string strCodigo)
        {
            return base.Channel.ConsultarAlumno(strCodigo);
        }
        
        public System.Threading.Tasks.Task<ProxyAlumno.AlumnoDC> ConsultarAlumnoAsync(string strCodigo)
        {
            return base.Channel.ConsultarAlumnoAsync(strCodigo);
        }
        
        public System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarAlumno()
        {
            return base.Channel.ListarAlumno();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarAlumnoAsync()
        {
            return base.Channel.ListarAlumnoAsync();
        }
        
        public System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarAlumnoNRC(string Nrc)
        {
            return base.Channel.ListarAlumnoNRC(Nrc);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarAlumnoNRCAsync(string Nrc)
        {
            return base.Channel.ListarAlumnoNRCAsync(Nrc);
        }
        
        public string ObtenerFacultadAlumno(string strIdAlum)
        {
            return base.Channel.ObtenerFacultadAlumno(strIdAlum);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerFacultadAlumnoAsync(string strIdAlum)
        {
            return base.Channel.ObtenerFacultadAlumnoAsync(strIdAlum);
        }
        
        public string ObtenerCarreraAlumno(string strIdAlum)
        {
            return base.Channel.ObtenerCarreraAlumno(strIdAlum);
        }
        
        public System.Threading.Tasks.Task<string> ObtenerCarreraAlumnoAsync(string strIdAlum)
        {
            return base.Channel.ObtenerCarreraAlumnoAsync(strIdAlum);
        }
        
        public System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarCarrera()
        {
            return base.Channel.ListarCarrera();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarCarreraAsync()
        {
            return base.Channel.ListarCarreraAsync();
        }
        
        public System.Collections.Generic.List<ProxyAlumno.AlumnoDC> ListarFacultad()
        {
            return base.Channel.ListarFacultad();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyAlumno.AlumnoDC>> ListarFacultadAsync()
        {
            return base.Channel.ListarFacultadAsync();
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAlumno))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioAlumno))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCG_Institutec/ServicioAlumno/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioAlumnoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioAlumno);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioAlumnoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioAlumno);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioAlumno,
        }
    }
}
