//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProxyUbigeo
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Departamentos", Namespace="http://schemas.datacontract.org/2004/07/WCG_Institutec")]
    public partial class Departamentos : object
    {
        
        private string IdDepartamentoField;
        
        private string nomDepartamentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDepartamento
        {
            get
            {
                return this.IdDepartamentoField;
            }
            set
            {
                this.IdDepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDepartamento
        {
            get
            {
                return this.nomDepartamentoField;
            }
            set
            {
                this.nomDepartamentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Provincias", Namespace="http://schemas.datacontract.org/2004/07/WCG_Institutec")]
    public partial class Provincias : object
    {
        
        private string IdProvinciaField;
        
        private string nomProvinciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdProvincia
        {
            get
            {
                return this.IdProvinciaField;
            }
            set
            {
                this.IdProvinciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomProvincia
        {
            get
            {
                return this.nomProvinciaField;
            }
            set
            {
                this.nomProvinciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distritos", Namespace="http://schemas.datacontract.org/2004/07/WCG_Institutec")]
    public partial class Distritos : object
    {
        
        private string IdDistritoField;
        
        private string nomDistritoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdDistrito
        {
            get
            {
                return this.IdDistritoField;
            }
            set
            {
                this.IdDistritoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nomDistrito
        {
            get
            {
                return this.nomDistritoField;
            }
            set
            {
                this.nomDistritoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyUbigeo.IServicioUbigeo")]
    public interface IServicioUbigeo
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDepartamentosResponse")]
        System.Collections.Generic.List<ProxyUbigeo.Departamentos> GetDepartamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDepartamentos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDepartamentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.Departamentos>> GetDepartamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetProvincias", ReplyAction="http://tempuri.org/IServicioUbigeo/GetProvinciasResponse")]
        System.Collections.Generic.List<ProxyUbigeo.Provincias> GetProvincias(string IdDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetProvincias", ReplyAction="http://tempuri.org/IServicioUbigeo/GetProvinciasResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.Provincias>> GetProvinciasAsync(string IdDepa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDistritos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDistritosResponse")]
        System.Collections.Generic.List<ProxyUbigeo.Distritos> GetDistritos(string IdDepa, string IdProv);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioUbigeo/GetDistritos", ReplyAction="http://tempuri.org/IServicioUbigeo/GetDistritosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.Distritos>> GetDistritosAsync(string IdDepa, string IdProv);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface IServicioUbigeoChannel : ProxyUbigeo.IServicioUbigeo, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class ServicioUbigeoClient : System.ServiceModel.ClientBase<ProxyUbigeo.IServicioUbigeo>, ProxyUbigeo.IServicioUbigeo
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioUbigeoClient() : 
                base(ServicioUbigeoClient.GetDefaultBinding(), ServicioUbigeoClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicioUbigeo.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), ServicioUbigeoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioUbigeoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioUbigeoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Collections.Generic.List<ProxyUbigeo.Departamentos> GetDepartamentos()
        {
            return base.Channel.GetDepartamentos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.Departamentos>> GetDepartamentosAsync()
        {
            return base.Channel.GetDepartamentosAsync();
        }
        
        public System.Collections.Generic.List<ProxyUbigeo.Provincias> GetProvincias(string IdDepa)
        {
            return base.Channel.GetProvincias(IdDepa);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.Provincias>> GetProvinciasAsync(string IdDepa)
        {
            return base.Channel.GetProvinciasAsync(IdDepa);
        }
        
        public System.Collections.Generic.List<ProxyUbigeo.Distritos> GetDistritos(string IdDepa, string IdProv)
        {
            return base.Channel.GetDistritos(IdDepa, IdProv);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ProxyUbigeo.Distritos>> GetDistritosAsync(string IdDepa, string IdProv)
        {
            return base.Channel.GetDistritosAsync(IdDepa, IdProv);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUbigeo))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicioUbigeo))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WCG_Institutec/ServicioUbigeo/");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioUbigeoClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicioUbigeo);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioUbigeoClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicioUbigeo);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicioUbigeo,
        }
    }
}
